# Mods to load on all Bots.
mods = ["best_bot", "rss", "policing"]

[bots]
  [bots.libera]
  type = "irc"
  admins = ["nick@user/nick"]
  server = "irc.libera.chat:6667"
  nick = "Guest1"

  [bots.discord]
  type = "discord"
  admins = ["1234"]
  mods = ["meme_police"]
  token = "$DISCORD_TOKEN"
  storage = "discord"

[storage]
  [storage.discord]
  type = "sqlite"
  file = "discord.sqlite"